### ISSUE TITLE
About the controler of the Realworld & PID Controller

### ISSUE THREAD

**Issue by Zedzou** [TJU-Aerial-Robotics/YOPO#11]
Hello. thank you for your code. I'm deploying your algorithm on a real machine, and want to know the __quad_pos_ctrl::ctrl_ref ctrl_msg__ in the _yopo_planner_node.cpp,_ is that your PID controler and open source? If I use the /mavros/setpoint_raw/global of the px4, can the same effect be achieved

**Comment by Lu-tju** [comment]
the ctrl_msg `quad_pos_ctrl::ctrl_ref`  is sent to our PID position controller (which is not open source because it is not my work). Then, the controller publishes `/mavros/setpoint_raw/attitude` to px4. I took a look at the msg of `/mavros/setpoint_raw/global`, it looks like using the GPS coordinates (lat, long, alt)

**Comment by Zedzou** [comment]
Thank you for your reply. That the msg  **/mavros/setpoint_raw/attitude,** I see that it not include the acceleration. the toipic **/mavros/setpoint_position/local** of the px4, It is the same type as the **ctrl_ref** message. Have you tried using PX4 control directly?

**Comment by Lu-tju** [comment]
Yes, `/mavros/setpoint_raw/attitude` does not include the acceleration. The controller can be divided into position control and attitude control. We use our PID position controller (position, velocity, acceleration, and yaw, due to the differential flatness) and PX4's attitude controller (thrust and angular rate). 
I have not directly used PX4 control, but it is allowed to use PX4 for position control directly.

**Comment by Zedzou** [comment]
Thank you. there is a [PID_Controller](https://github.com/TJU-Aerial-Robotics/PID_Controller), this is the one you use?

**Comment by Lu-tju** [comment]
haha yes, I thought it was private...

**Comment by Zedzou** [comment]
hahaha, thank you very much. I will do some experiments on the real robot. thank you.

**Comment by Lu-tju** [comment]
But in the latest high-speed experiment, I did not use this controller, the error is larger with the speed increasing.
Anyway, start slow.
